language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  git lfs pull
# command to run tests
script:
  coverage run --source=nassl setup.py test
after_success:
  coveralls
